function(my_print_cmake_data)
    message("==my_print_cmake_data==")
    message("${CMAKE_PROJECT_NAME}-${CMAKE_PROJECT_VERSION}-${GIT_SHORT_SHA}-${CMAKE_SYSTEM_NAME}-${CMAKE_BUILD_TYPE}-${CMAKE_CXX_COMPILER_ID}-${CMAKE_CXX_COMPILER_VERSION}")
    message("PROJECT_SOURCE_DIR         -> ${PROJECT_SOURCE_DIR}")
    message("PROJECT_BINARY_DIR         -> ${PROJECT_BINARY_DIR}")
    message("CMAKE_SOURCE_DIR           -> ${CMAKE_SOURCE_DIR}")
    message("CMAKE_BINARY_DIR           -> ${CMAKE_BINARY_DIR}")
    message("CMAKE_CURRENT_SOURCE_DIR   -> ${CMAKE_CURRENT_SOURCE_DIR}")
    message("CMAKE_CURRENT_BINARY_DIR   -> ${CMAKE_CURRENT_BINARY_DIR}")
    message("CMAKE_PROJECT_NAME         -> ${CMAKE_PROJECT_NAME}")
    message("CMAKE_PROJECT_VERSION      -> ${CMAKE_PROJECT_VERSION}")
    message("CMAKE_SYSTEM_NAME          -> ${CMAKE_SYSTEM_NAME}")
    message("CMAKE_SYSTEM_PROCESSOR     -> ${CMAKE_SYSTEM_PROCESSOR}")
    message("CMAKE_SYSTEM_VERSION       -> ${CMAKE_SYSTEM_VERSION}")
    message("CMAKE_DL_LIBS              -> ${CMAKE_DL_LIBS}")

    message("=========Default values=========") 
    message("CMAKE_CONFIGURATION_TYPES  -> ${CMAKE_CONFIGURATION_TYPES}")
    message("CMAKE_C_FLAGS              -> ${CMAKE_C_FLAGS}")
    message("CMAKE_C_FLAGS_DEBUG        -> ${CMAKE_C_FLAGS_DEBUG}")
    message("CMAKE_C_FLAGS_RELEASE      -> ${CMAKE_C_FLAGS_RELEASE}")
    message("CMAKE_CXX_FLAGS            -> ${CMAKE_CXX_FLAGS}")
    message("CMAKE_CXX_FLAGS_DEBUG      -> ${CMAKE_CXX_FLAGS_DEBUG}")
    message("CMAKE_CXX_FLAGS_RELEASE    -> ${CMAKE_CXX_FLAGS_RELEASE}")

    message("CMAKE_EXE_LINKER_FLAGS       -> ${CMAKE_EXE_LINKER_FLAGS}")
    message("CMAKE_MODULE_LINKER_FLAGS    -> ${CMAKE_MODULE_LINKER_FLAGS}")
    message("CMAKE_SHARED_LINKER_FLAGS    -> ${CMAKE_SHARED_LINKER_FLAGS}")
    message("CMAKE_STATIC_LINKER_FLAGS    -> ${CMAKE_STATIC_LINKER_FLAGS}")
    message("=========Default values=========")
    message("~~my_print_cmake_data~~")
endfunction()

function(my_print_platform_data)
    message("==my_print_platform_data==")
    if (WIN32)
        message("INFO: OS: WIN32")
    elseif (UNIX AND NOT APPLE)
        message("INFO: OS: LINUX")
    else()
        message(FATAL_ERROR "INFO: OS: UNKNOWN")
    endif()
    message("~~my_print_platform_data~~")
endfunction(my_print_platform_data)

function(my_print_compiler_data)
    if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
      message("INFO: Compiler: CLANG")
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        message("INFO: Compiler: GCC")
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
        message("INFO: Compiler: INTEL")
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        message("INFO: Compiler: MSVC")
    else()
        message(FATAL_ERROR "INFO: Compiler: UNKNOWN")
    endif()
endfunction(my_print_compiler_data)

function(my_print_generator_data)
    message("INFO: Generator: ${CMAKE_GENERATOR}")
endfunction(my_print_generator_data)

